name: dockerhub

on:
  release:
    types: [published]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.MCMICRO_USERNAME }}
          password: ${{ secrets.MCMICRO_TOKEN }}
      -
        name: Build and push the standard image
        id: docker_build_standard
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: labsyspharm/s3segmenter:${{ github.event.release.tag_name }}
      -
        name: Build and push the large-scale image
        id: docker_build_large
        uses: docker/build-push-action@v2
        with:
          context: large
          push: true
          tags: labsyspharm/s3segmenter:${{ github.event.release.tag_name }}-large
      -
        name: Image digest
        run: |
          echo ${{ steps.docker_build_standard.outputs.digest }}
          echo ${{ steps.docker_build_large.outputs.digest }}
